name: Github Actions Tests

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

env:
  LOCALSTACK_TAG: 3.3

jobs:
  detect-secrets:
    name: Detect secrets
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Cache Localstack
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57  # v4.2.0
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-localstack-${{ env.LOCALSTACK_TAG }}
          restore-keys: ${{ runner.os }}-localstack-
      - name: Load cached Localstack image
        run: |
          if [ -f /tmp/.docker-cache/localstack.tar ]; then
            docker load --input /tmp/.docker-cache/localstack.tar
          fi
      - name: Pull Localstack & save to cache (if not cached)
        run: |
          if [ ! -f /tmp/.docker-cache/localstack.tar ]; then
            docker pull localstack/localstack:${{ env.LOCALSTACK_TAG }}
            mkdir -p /tmp/.docker-cache
            docker save -o /tmp/.docker-cache/localstack.tar localstack/localstack:${{ env.LOCALSTACK_TAG }}
          fi
      - name: Set up JDK 21
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Cache Maven packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57  # v4.2.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Run tests
        run: mvn --no-transfer-progress clean verify

  dependency-review:
    name: Dependency Review scan
    uses: alphagov/pay-ci/.github/workflows/_run-dependency-review.yml@master
